### PR TITLE
TNW-Project clone

### PR DESCRIPTION
**Pull request by denisdiaconu**
We build a copy of the The Next Web website. We used Grid for the position of the items and media queries for the phone and tablet version of the page.

### CODE REVIEW

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

* [x] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [x] CSS styles should use [media queries](https://www.w3schools.com/css/css_rwd_mediaqueries.asp) for 2 breakpoints ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/breakpoints_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))

* [x]  No small break point as it is mobile first and the base styles are for the mobile screen. ([Screenshot on mobile first approach](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/mobile_first.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540217/))
  * medium: min-width around 768px
  * large: min-width 1024px

* [x]  Fix the navbar text on medium screen ([link to page](https://thenextweb.com/))

| Yours | Original |
| --- | --- |
| image | image |

- [x] on the mobile screen there's a huge empty space between the **Latest funding** section and the Categories section  ([link to page](https://thenextweb.com/))
image

- [x] on the categories section, mobile screen, add some space before the text on the top ([link to page](https://thenextweb.com/))
image

- [x] overall, please examine the original website and try to make the elements look like them, especially the **cards** ([link to page](https://thenextweb.com/))




### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by denisdiaconu** [comment]
CSS styles for 2 breakpoints. 
- Removing small breakpoints.
- Changed the entire page from desktop to phone.
- Fix navbar text on medium screen.
- remove space between the latest funding section and categories.
- Fixed the text space.

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team. 💻 👀 ✨ 

## However, there are some changes required 👀 🧰 🔨 🔧 
- [x] In mobile view I'm able to scroll a bit to the right because your page design overflows horizontally. Please fix it so that on mobile view there is no horizontal page overflow.
image
- [x] Also, on mobile view, your thumbnails become stretched. Please fix this.
image
- [x] I'm also able to scroll horizontally on tablet view. Please fix your page design so that there is no horizontal overflow here either.
image

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by denisdiaconu** [comment]
Fixed the horizontal scrolling for the tablet and the phone.
Fixed the thumbnails.

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @denisdiaconu and @billodiallo   ! :wave: :wave:

#### You have done well so far :clap: However, for this project to be approved, you have to fix the conflicts in this PR. Kindly work on it and submit for another code review.



__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by denisdiaconu** [comment]
Fixed the conflicts.

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @denisdiaconu and @billodiallo  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
